version: '3'

services:
  sentinel:
    image: {{ sentinel_image }}
    container_name: sentinel
    restart: always
    environment:
      - DEBUG=false
      - RPCUSER={{ xazabd_rpc_user }}
      - RPCPASSWORD={{ xazabd_rpc_password }}
      - RPCHOST={{ private_ip }}
      - RPCPORT={{ xazabd_rpc_port }}
      # Sentinel only supports mainnet and testnet at the moment
      - NETWORK={{ 'mainnet' if xazab_network == 'mainnet' else 'testnet' }}
      # Bypass scheduler
      - SENTINEL_ARGS=-b
