---

- name: import multifaucet donation address
  command: xazab-cli {{ faucet_rpc_args }} importprivkey {{ faucet_privkey }}

- name: create multifaucet dirs
  file: path='{{ item }}' state=directory recurse=true
  with_items:
    - '{{ xazabd_home }}/multifaucet/multifaucet'

- name: multifaucet config
  template:
    src: '{{ item }}'
    dest: '{{ xazabd_home }}/multifaucet/{{ item }}'
  with_items:
    - docker-compose.yml
    - multifaucet/Dockerfile
    - multifaucet/db.conf.php
    - multifaucet/wallet.conf.php
    - multifaucet/faucet.conf.php
    - multifaucet/php.ini
    - init.sql

- name: multifaucet service
  docker_compose:
    project_src: '{{ xazabd_home }}/multifaucet'
    state: present
    build: yes
